### ISSUE TITLE
needs description

### ISSUE THREAD

**Issue by josmardias** [conceptho/lamb-wrap#1]
On the project main page there is a `No description or website provided.` :-1: 
Please, provide a short description to be shown :+1:

**Comment by josmardias** [comment]
@andremetzen 
I recall a conversation with you about a role based data access, acting as a filtering layer, on top of a ORM, that filter accessible data regarding a role permission configuration.

Is this project something related?

**Comment by andremetzen** [comment]
@josmardias We're still trying to figure out what will come into this repo. But our initial goal is to have some sort of entrypoint to wrap lambda functions with permissions over resources and attributes. 

Once we have a clear idea of what this will be, we'll definitively write a good description/docs.

**Comment by josmardias** [comment]
You can copy and paste this answer to the README.md :laughing:

**Comment by josmardias** [comment]
lamb:
http://static.independent.co.uk/s3fs-public/styles/article_large/public/thumbnails/image/2016/02/23/20/web-happy-lamb.jpg

wrap:
http://www.dairyqueen.com/Global/Food/Kids-Chk-Wrap.png?width=&height=810

lol

**Comment by josmardias** [comment]
Since we have a good README now I'm closing this issue :dancer:
